name: contrique
channels:
  - conda-forge
  - nodefaults
dependencies:
  - certifi=2021.5.30
  - pip=21.2.2
  - python=3.6.13
  - setuptools=58.0.4
  - sqlite=3.45.3
  - wheel=0.37.1
  - pip:
    - dataclasses==0.8
    - joblib==1.1.1
    - numpy==1.16.1
    - pandas==0.24.2
    - pickleshare==0.7.5
    - pillow==8.4.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - scikit-learn==0.24.2
    - scikit-video==1.1.11
    - scipy==1.2.1
    - six==1.16.0
    - threadpoolctl==3.1.0
    - torch==1.10.*
    - torchvision==0.11.*
    - typing-extensions==4.1.1
